### ISSUE TITLE
Small affordances

### ISSUE THREAD

**Issue by HamishMacEwan** [Xtrimmer/lndecode#1]
Thanks very much for the service.  I would like to make a couple of suggestions.

1. Could the decoded be passed in the url?  And once entered manually, that decode will return the URL including the invoice string? eg. `https://lndecode.com/?lnbc1230n1pw4uy6app56445r7papdht2v5ypkhsztm8g4d8ma9zzavca0gleed3xucfuywsdqu2askcmr9wssx7e3q2dshgmmndp5scqzpgxqrrss3024un2qyz28m4psh9wkccz4vhdy0lfj6mtpq0v7ka0esc7w3575kxz4qv5ca0uvrhx59resnqfhqcw948cltwr58qpq8azellxjgtcpag0xva`

2. Could the input field do a little pre-processing to trim fore and aft? It's unfortunate that strings are condemned as invalid due to a carriage return at the end of the string.

Again, thank for something so neat and simple my nitpicks stand out the more.

**Comment by Xtrimmer** [comment]
I have made the appropriate changes. Whitespace will be trimmed form both sides of the invoice string and the invoice string can be passed in as a query parameter with the name 'invoice'
Here is an example:

https://lndecode.com/?invoice=lnbc1pvjluezpp5qqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqypqdpl2pkx2ctnv5sxxmmwwd5kgetjypeh2ursdae8g6twvus8g6rfwvs8qun0dfjkxaq8rkx3yf5tcsyz3d73gafnh3cax9rn449d9p5uxz9ezhhypd0elx87sjle52x86fux2ypatgddc6k63n7erqz25le42c4u4ecky03ylcqca784w

Note: It may take a couple days for the changes to be propagated to all the website endpoints worldwide.

**Comment by HamishMacEwan** [comment]
Fantastic,  thank you!
