### ISSUE TITLE
Decode in real time when pasting bolt11

### ISSUE THREAD

**Issue by patrickReiis** [Xtrimmer/lndecode#10]
Hi, I started to get crazy when I was pasting multiple different bolt11 and the payment info always stayed the same, then I realized that I didn't click in the "Decode" button, it would be good if it updated the payment info dynamically.

**Comment by Xtrimmer** [comment]
Like fiat, buttons are rather conventional. A reactive approach is superior. The button has been removed, and decoding now initiates automatically upon pasting. Thanks for the suggestion. I have updated the web servers but content delivery network may take up to 48 hours to update all caches worldwide.

**Comment by patrickReiis** [comment]
Wow I did not think you would reply, thank you very much! I've been using your website everyday to implement a lightning feature into the company I work for.

**Comment by Xtrimmer** [comment]
That's great! Your suggestion was good, and not too hard to pull off. Happy to oblige.
