### ISSUE TITLE
simnet addresses not working

### ISSUE THREAD

**Issue by ottosuess** [Xtrimmer/lndecode#2]
lnsb10n1pwemvgrpp5682zm9zc4jp3yzr69lvqnwxzj3e9qh9q0xyf8fq6xed6pgex37rqdqqcqzpgxq97zvuqh6r9xwxyg5kwlaz3tkm00fx6zyr7m43lp95tk0drkng2ysex7xsxva9ky3ggw3uuae2rdfvls0j2m3vdxzs7vdxxvskxguds3q0ewxqqh7nys7

```
Uh-Oh! Something is not quite right with this request.
Malformed request: unknown prefix
```

**Comment by Xtrimmer** [comment]
Looking at the [BOLT #11 specification that talks about the prefix](https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md#human-readable-part), I see no mention of this code for simnet but it also doesn't appear to provide a comprehensive list of all possible prefixes. Can you point me to where this prefix you are requesting is documented?

**Comment by ottosuess** [comment]
i don't know if there is any documentation about this, but lnd uses it.
here is an example from lnd tests:
https://github.com/lightningnetwork/lnd/blob/master/zpay32/invoice_test.go#L745

**Comment by Xtrimmer** [comment]
I have updated the source files and deployed to the web hosting service. It may take up to 24 hours to propagate to all the content delivery web endpoints worldwide.

**Comment by Xtrimmer** [comment]
Looks like the endpoints have the new version deployed and is working. Closing.
https://lndecode.com/?invoice=lnsb10n1pwemvgrpp5682zm9zc4jp3yzr69lvqnwxzj3e9qh9q0xyf8fq6xed6pgex37rqdqqcqzpgxq97zvuqh6r9xwxyg5kwlaz3tkm00fx6zyr7m43lp95tk0drkng2ysex7xsxva9ky3ggw3uuae2rdfvls0j2m3vdxzs7vdxxvskxguds3q0ewxqqh7nys7
