### ISSUE TITLE
No Destination in the Decode

### ISSUE THREAD

**Issue by HamishMacEwan** [Xtrimmer/lndecode#4]
Hi,

Here's an invoice, and decode, made on Zeus connected to myNodeBTC.  http://bit.ly/30da2Th

No destination (AKA public key?)

But.

```
myNode:~ $ lncli decodepayreq lnbc1020n1p0pc9yxpp5n5e9hw0gp4j5m2vqmnhr0qeke0yfm6rgdm98yaqs94303wlkxhesdp8f9h8vmmfvdjjqenjdakjqkn9w4ej7mtefehkgegcqzpgxqypr9qfz0cg9hqkjj9ptdcxek59v833suuzsgezx5rmlg69qpj6ezrmlj3zmghpfqvhscxj6k3qf9qzj5szpp8yjnjqsfxaswhf2jeppft35spfjscsx
{
    "destination": "024782abc1c13802508f4c7b2c2c8b1f5ebc2b596bee0b2ff338c382e7ca28df77",
    "payment_hash": "9d325bb9e80d654da980dcee378336cbc89de8686eca7274102d62f8bbf635f3",
    "num_satoshis": "102",
    "timestamp": "1578898566",
    "expiry": "36000",
    "description": "Invoice from Zeus/myNode",
    "description_hash": "",
    "fallback_addr": "",
    "cltv_expiry": "40",
    "route_hints": [
    ]
}
```

What am I missing?

**Comment by Xtrimmer** [comment]
Destination is the public key of the target node. It can optionally be set before encoding to include the pubkey as an 'n' field. If this is not set before encoding then the destination pubkey won't be added as an 'n' field. The pubkey can be extracted from the signature during decoding.  There is no function in this decoder to do the signature recovery as it is now but I suppose this could be added.

**Comment by HamishMacEwan** [comment]
Thanks, for the explanation.  It did seem most unlikely that the destination was omitted, or how does one get paid... 

Your call on whether you want to explicitly expose that information.  It would make it more comprehensive...
