### ISSUE TITLE
1+ BTC invoices: undefined amount multiplier

### ISSUE THREAD

**Issue by ghost** [Xtrimmer/lndecode#5]
Any invoice with an amount greater than 1 BTC will produce an `undefined amount multiplier` error. 

```
Uh-Oh! Something is not quite right with this request.
Malformed request: undefined amount multiplier
```

The [spec](https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md#human-readable-part) says `amount: optional number in that currency, followed by an optional multiplier letter.` 

But in the logic here: https://github.com/Xtrimmer/lndecode/blob/master/js/decoder.js#L90

it says: `A reader SHOULD fail if amount is followed by anything except a defined multiplier.`

Here's a valid invoice that'll fail because it's a 1btc invoice `lnbcrt11p044hvepp5mfyxfq7m7jj60wskkh8eaz74ppfy2x6rnnj6gmy3g7r297kavfdqdqqcqzpgsp5tcm44lr40gn78g9qvz0r2hysqluwz6jlatyqee4t7lwjl8ndcnjs9qy9qsqhfxk8a9f86kwuh5g64jewkrnrgqqy2kdm3nkn6rmgshu6hs7c0yzq8t4pvm324vll0hmld0mnf58c6y0598sp880kuyte7m3a52aa9qp9jdf0m`

**Comment by Xtrimmer** [comment]
Thank you for the report. The defined multiplier used to be required but it looks like it is not now. I'll look into getting this updated soon.

**Comment by Xtrimmer** [comment]
I believe I have fixed the issue. If you clone the repository and run from that, the invoice you provided will be decoded as expected. I will upload the fix to the web server tomorrow and from there it should propagate to all content delivery endpoints worldwide within 48 hours. Once live, I'll close this issue as fixed.

**Comment by Xtrimmer** [comment]
Looks like the files have propagated to the web server and is now working as expected.

https://lndecode.com/?invoice=lnbcrt11p044hvepp5mfyxfq7m7jj60wskkh8eaz74ppfy2x6rnnj6gmy3g7r297kavfdqdqqcqzpgsp5tcm44lr40gn78g9qvz0r2hysqluwz6jlatyqee4t7lwjl8ndcnjs9qy9qsqhfxk8a9f86kwuh5g64jewkrnrgqqy2kdm3nkn6rmgshu6hs7c0yzq8t4pvm324vll0hmld0mnf58c6y0598sp880kuyte7m3a52aa9qp9jdf0m
